### ISSUE TITLE
Additional German translations

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/flexboxfroggy#24]
There are a few new German translations left to do.

In https://github.com/thomaspark/flexboxfroggy/blob/gh-pages/lang/de/index.html#L25:
* "Level"

In https://github.com/thomaspark/flexboxfroggy/blob/gh-pages/js/messages.js:
* "Reset"
* "Are you sure you want to reset the game?\n\nYour saved progress will be lost and you\'ll be sent to the start of the game."

Can someone help with these? (@tfrommen :wink:)

**Comment by tfrommen** [comment]
No problem, I will update the German translations in a second.

However, I would strongly suggest to fully separate any (to-be-translated) strings from the rest of the _app_, and thus have only **one** `index.html` that reads the user's language and then uses the according strings (with a fallback to English for any missing translation). Otherwise, keeping the translations up-ot-date is a very tedious task. For instance, adding a new language would require all the other `index.html` files. Having a separate file (e.g., `strings.js`, or even `strings.json`) and then _reading_ the according string is the way to go.

```js
var strings = {
    game: {
        level1: {
            en: '...',
            de: '...',
        }
    },
    messages: {
        warningReset: {
            en: '...',
            de: '...',
        }
    }
};

var getString = function( lang, id ) {
    var properties = id.split( '.' ),
        property,
        value = strings;

    while( properties.length ) {
        property = properties.shift();

        if ( ! value.property ) {
            return 'return empty string or something else here';
        }

        value = value.property;
    }

    if ( value.lang ) {
        return value.lang;
    } else if( value.en ) {
        return value.en;
    } else {
        retutn 'same error string from above or so...':
    }
};
```

Note this is just a quick write-up. Please don't take it as-is. :)

**Comment by thomaspark** [comment]
Thanks @tfrommen, the way languages are handled is definitely due for a refactor. Your approach looks good to me, though I might prefer to use a query string than automatically detect the user language. I'll merge your changes for now and hopefully get to that soon.
